/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#161544",
        "error": "#ba1a1a",
        "tertiary-container": "#a25100",
        "on-tertiary-fixed-variant": "#713700",
        "primary-fixed": "#e2dfff",
        "primary": "#3f3bbd",
        "tertiary": "#7e3e00",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f3f8",
        "primary-container": "#5856d6",
        "inverse-on-surface": "#f0f0f5",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdcc6",
        "outline": "#777585",
        "surface-variant": "#e2e2e7",
        "secondary-fixed-dim": "#c3c1fa",
        "outline-variant": "#c7c4d6",
        "tertiary-fixed-dim": "#ffb785",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e2dfff",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3034",
        "surface-bright": "#f9f9fe",
        "surface-container": "#ededf2",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#c8c7ff",
        "surface-dim": "#d9dade",
        "on-surface-variant": "#464554",
        "on-primary-container": "#e7e4ff",
        "surface-container-high": "#e8e8ed",
        "on-tertiary-fixed": "#301400",
        "on-secondary-container": "#515182",
        "on-surface": "#1a1c1f",
        "secondary": "#5a598b",
        "surface": "#f9f9fe",
        "background": "#f9f9fe",
        "on-background": "#1a1c1f",
        "primary-fixed-dim": "#c2c1ff",
        "error-container": "#ffdad6",
        "surface-tint": "#4f4ccd",
        "on-primary": "#ffffff",
        "inverse-primary": "#c2c1ff",
        "on-tertiary-container": "#ffe1cf",
        "on-primary-fixed": "#0c006a",
        "on-secondary-fixed-variant": "#424272",
        "surface-container-highest": "#e2e2e7",
        "on-primary-fixed-variant": "#3631b4"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
